### ISSUE TITLE
data collection failing due to permission

### ISSUE THREAD

**Issue by abbyers73** [Relkci/Zabbix_Bandwidth-vnstat#3]
Environment is all RHEL 8 

Tested running command from config local on server successfully with specific NIC however the agent isn't reporting data back to zabbix app server.

zabbix_agentd -t bandwidth.vnstat.data[ens18]
bandwidth.vnstat.data[ens18]                  [t|1;ens18;2022-01-14;8619991;1807016;10427007;204;2022-01;8619991;1807016;10427007;8;8619991;1807016;10427007]

![zabbix_bandwidth](https://user-images.githubusercontent.com/48621689/149571911-dfbaac93-8840-4d9a-a334-37fce3472f5a.jpg)

**Comment by backl1n** [comment]
have you found a solution of this problem or you have find other template for see usage of bandwidth  @abbyers73 ? please reply me

**Comment by abbyers73** [comment]
I abandoned this project and found a alternative solution.

**Comment by backl1n** [comment]
what is your alternative solution  ? @abbyers73
